name: Unit Tests (Cross-Platform)

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  run-tests:
    name: Run Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' # Optional: Caches pip dependencies
          cache-dependency-path: 'src/dev/cassitly/python/requirements.txt' # Optional: Specifies the dependency file for caching

      - name: Install dependencies
        run: |
          npm install yaml chalk --save-dev
          cd testing/cassitly
          npm install
          cd ../..
          pip install -r src/dev/cassitly/python/requirements.txt          

      - name: Run test runner
        shell: bash
        run: |
          echo "Running JS test runner..."
          node testing/runner.js
